# Generated by Django 2.2.1 on 2019-05-29 08:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import webcam.models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0004_auto_20170703_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestshot',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='bestshot',
            name='image',
            field=models.ImageField(upload_to=webcam.models.set_webcam_image_folder, verbose_name='immagine'),
        ),
        migrations.AlterField(
            model_name='bestshot',
            name='webcam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcam.Webcam', verbose_name='webcam'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='active',
            field=models.BooleanField(default=True, verbose_name='attiva'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='latitude',
            field=models.CharField(max_length=50, verbose_name='latitudine'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='longitude',
            field=models.CharField(max_length=50, verbose_name='longitudine'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='technology',
            field=models.CharField(max_length=128, verbose_name='tecnologia'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='webcam',
            name='web',
            field=models.URLField(blank=True, null=True, verbose_name='pagina dedicata'),
        ),
    ]
