# Generated by Django 2.2.1 on 2019-05-29 08:40

import blog.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161227_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='autore'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creazione'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='enable_comments',
            field=models.BooleanField(default=True, verbose_name='abilita commenti'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.set_entry_image_folder, verbose_name='immagine'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='index_words',
            field=models.IntegerField(verbose_name='numero parole home'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modifica'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='num_read',
            field=models.IntegerField(blank=True, default=0, verbose_name='numero letture'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='published',
            field=models.BooleanField(default=False, verbose_name='pubblicato'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='related_entries',
            field=models.ManyToManyField(blank=True, related_name='_entry_related_entries_+', to='blog.Entry', verbose_name='articoli correlati'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='valori separati da virgole', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='testo'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=128, verbose_name='titolo'),
        ),
    ]
