# Generated by Django 2.2.1 on 2019-05-29 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20170519_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationbookmark',
            name='insertion_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='inserimento'),
        ),
        migrations.AlterField(
            model_name='stationbookmark',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='realtime.Station', verbose_name='stazione'),
        ),
        migrations.AlterField(
            model_name='stationbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='utente'),
        ),
    ]
