# Generated by Django 2.2 on 2019-07-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treenav', '0003_auto_20190401_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='label_it',
        ),
    ]
