""" Defines the keys to be used in the data dictionary
"""

DATA_LABELS = {
    'DATETIME': 'datetime',
    'TIME': 'time',
    'DATE': 'date',
    'TEMP': 'temperature',
    'TEMP_MAX': 'temperature_max',
    'TEMP_MAX_TIME': 'temperature_max_time',
    'TEMP_MIN': 'temperature_min',
    'TEMP_MIN_TIME': 'temperature_min_time',
    'HUMIDITY': 'relative_humidity',
    'HUMIDITY_MAX': 'relative_humidity_max',
    'HUMIDITY_MAX_TIME': 'relative_humidity_max_time',
    'HUMIDITY_MIN': 'relative_humidity_min',
    'HUMIDITY_MIN_TIME': 'relative_humidity_min_time',
    'DEW': 'dewpoint',
    'DEW_MAX': 'dewpoint_max',
    'DEW_MAX_TIME': 'dewpoint_max_time',
    'DEW_MIN': 'dewpoint_min',
    'DEW_MIN_TIME': 'dewpoint_min_time',
    'PRESSURE': 'pressure',
    'PRESSURE_MAX': 'pressure_max',
    'PRESSURE_MAX_TIME': 'pressure_max_time',
    'PRESSURE_MIN': 'pressure_min',
    'PRESSURE_MIN_TIME': 'pressure_min_time',
    'WIND': 'wind_strength',
    'WIND_DIR': 'wind_dir',
    'WIND_MAX': 'wind_strength_max',
    'WIND_DIR_MAX': 'wind_dir_max',
    'WIND_MAX_TIME': 'wind_max_time',
    'RAIN': 'rain',
    'RAIN_RATE': 'rain_rate',
    'RAIN_RATE_MAX': 'rain_rate_max',
    'RAIN_RATE_MAX_TIME': 'rain_rate_max_time',
    'RAIN_MONTH': 'rain_month',
    'RAIN_YEAR': 'rain_year'
}

AIRQUALITY_DATA_LABELS = {
    'DATETIME': 'datetime',
    'AIR_QUALITY_INDEX': 'air_quality_index',
    'PM1': 'pm1',
    'PM1_MAX': 'pm1_max',
    'PM1_MAX_TIME': 'pm1_max_time',
    'PM1_MIN': 'pm1_min',
    'PM1_MIN_TIME': 'pm1_min_time',
    'PM25': 'pm25',
    'PM25_MAX': 'pm25_max',
    'PM25_MAX_TIME': 'pm25_max_time',
    'PM25_MIN': 'pm25_min',
    'PM25_MIN_TIME': 'pm25_min_time',
    'PM10': 'pm10',
    'PM10_MAX': 'pm10_max',
    'PM10_MAX_TIME': 'pm10_max_time',
    'PM10_MIN': 'pm10_min',
    'PM10_MIN_TIME': 'pm10_min_time',
}
