""" Defines the keys to be used in the data dictionary
"""

DATA_LABELS = {
    'DATETIME': 'datetime',
    'TIME': 'time',
    'DATE': 'date',
    'TEMP': 'temp',
    'TEMP_MAX': 'temp_max',
    'TEMP_MAX_TIME': 'temp_max_time',
    'TEMP_MIN': 'temp_min',
    'TEMP_MIN_TIME': 'temp_min_time',
    'HUMIDITY': 'relative_humidity',
    'HUMIDITY_MAX': 'relative_humidity_max',
    'HUMIDITY_MAX_TIME': 'relative_humidity_max_time',
    'HUMIDITY_MIN': 'relative_humidity_min',
    'HUMIDITY_MIN_TIME': 'relative_humidity_min_time',
    'DEW': 'dew',
    'DEW_MAX': 'dew_max',
    'DEW_MAX_TIME': 'dew_max_time',
    'DEW_MIN': 'dew_min',
    'DEW_MIN_TIME': 'dew_min_time',
    'PRESSURE': 'pressure',
    'PRESSURE_MAX': 'pressure_max',
    'PRESSURE_MAX_TIME': 'pressure_max_time',
    'PRESSURE_MIN': 'pressure_min',
    'PRESSURE_MIN_TIME': 'pressure_min_time',
    'WIND': 'wind',
    'WIND_DIR': 'wind_dir',
    'WIND_MAX': 'wind_max',
    'WIND_DIR_MAX': 'wind_dir_max',
    'WIND_MAX_TIME': 'wind_max_time',
    'RAIN': 'rain',
    'RAIN_RATE': 'rain_rate',
    'RAIN_RATE_MAX': 'rain_rate_max',
    'RAIN_RATE_MAX_TIME': 'rain_rate_max_time',
    'RAIN_MONTH': 'rain_month',
    'RAIN_YEAR': 'rain_year'
}
