# Generated by Django 2.2.1 on 2019-05-29 08:40

import ckeditor_uploader.fields
import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0016_auto_20171106_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(verbose_name='data e ora'),
        ),
        migrations.AlterField(
            model_name='data',
            name='dewpoint',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='dewpoint'),
        ),
        migrations.AlterField(
            model_name='data',
            name='dewpoint_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='dewpoint massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='dewpoint_max_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora dewpoint massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='dewpoint_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='dewpoint minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='dewpoint_min_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora dewpoint minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pressione'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressure_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pressione massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressure_max_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora pressione massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressure_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pressione minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='pressure_min_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora pressione minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='accumulo precipitazioni'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain_month',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='accumulo mensile precipitazioni'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='rateo precipitazioni'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain_rate_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='rateo massimo precipitazioni'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain_rate_max_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora rateo massimo precipitazioni'),
        ),
        migrations.AlterField(
            model_name='data',
            name='rain_year',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='accumulo annuale precipitazioni'),
        ),
        migrations.AlterField(
            model_name='data',
            name='relative_humidity',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='umidità relativa'),
        ),
        migrations.AlterField(
            model_name='data',
            name='relative_humidity_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='umidità relativa massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='relative_humidity_max_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora umidità relativa massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='relative_humidity_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='umidità relativa minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='relative_humidity_min_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora umidità relativa minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Station', verbose_name='stazione'),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperatura'),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperatura massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature_max_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora temperatura massima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperatura minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='temperature_min_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora temperatura minima'),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind_dir',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='direzione vento'),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind_dir_max',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='direzione vento massimo'),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind_max_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ora vento massimo'),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind_strength',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='vento'),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind_strength_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='vento massimo'),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='description',
            field=models.TextField(verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='dataformat',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='pressure_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pressione massima'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='pressure_mean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pressione media'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='pressure_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='pressione minima'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='rain',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='accumulo precipitazioni'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='relative_humidity_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='umidità relativa massima'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='relative_humidity_mean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='umidità relativa media'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='relative_humidity_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='umidità relativa minima'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Station', verbose_name='stazione'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperatura massima'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='temperature_mean',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperatura media'),
        ),
        migrations.AlterField(
            model_name='historicdata',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='temperatura minima'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='alpha2_code',
            field=models.CharField(max_length=2, verbose_name='alpha2 code'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='alpha3_code',
            field=models.CharField(max_length=3, verbose_name='alpha3 code'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='numeric_code',
            field=models.CharField(max_length=4, verbose_name='codice numerico'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='rank',
            field=models.IntegerField(verbose_name='importanza'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='address',
            field=models.CharField(max_length=255, verbose_name='indirizzo'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='city',
            field=models.CharField(max_length=128, verbose_name='città'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='climate',
            field=models.TextField(verbose_name='microclima'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='data_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL dati realtime'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='elevation',
            field=models.IntegerField(verbose_name='altitudine'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='elevation_ground',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='altezza dal suolo (m)'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='firstname',
            field=models.CharField(max_length=128, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='installation_position',
            field=models.CharField(max_length=255, verbose_name='ubicazione'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='installation_type',
            field=models.CharField(max_length=255, verbose_name='tipo di installazione'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='lastname',
            field=models.CharField(max_length=128, verbose_name='cognome'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='lat',
            field=models.CharField(max_length=128, verbose_name='latitudine'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='lng',
            field=models.CharField(max_length=128, verbose_name='longitudine'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='mean_year_rain',
            field=models.IntegerField(verbose_name='precipitazione media annua (mm)'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='nation',
            field=models.CharField(max_length=128, verbose_name='nazione'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='province',
            field=models.CharField(max_length=2, verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='software_model',
            field=models.CharField(max_length=255, verbose_name='modello software'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='station_description',
            field=models.TextField(verbose_name='descrizione stazione'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='station_model',
            field=models.CharField(max_length=255, verbose_name='modello stazione'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='web_site_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='URL sito web'),
        ),
        migrations.AlterField(
            model_name='netrequest',
            name='webcam_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Webcam URL'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='province',
            name='rank',
            field=models.IntegerField(verbose_name='importanza'),
        ),
        migrations.AlterField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Region', verbose_name='regione'),
        ),
        migrations.AlterField(
            model_name='radarcolorconversion',
            name='converted_color',
            field=colorful.fields.RGBColorField(verbose_name='colore finale'),
        ),
        migrations.AlterField(
            model_name='radarcolorconversion',
            name='original_color',
            field=colorful.fields.RGBColorField(verbose_name='colore iniziale'),
        ),
        migrations.AlterField(
            model_name='radarcolorconversion',
            name='tolerance',
            field=models.IntegerField(verbose_name='tolleranza'),
        ),
        migrations.AlterField(
            model_name='radarconvertparams',
            name='param_name',
            field=models.CharField(max_length=50, verbose_name='nome parametro'),
        ),
        migrations.AlterField(
            model_name='radarconvertparams',
            name='param_value',
            field=models.CharField(max_length=50, verbose_name='valore parametro'),
        ),
        migrations.AlterField(
            model_name='radarsnapshot',
            name='datetime',
            field=models.DateTimeField(verbose_name='data e ora'),
        ),
        migrations.AlterField(
            model_name='radarsnapshot',
            name='filename',
            field=models.CharField(max_length=128, verbose_name='nome file'),
        ),
        migrations.AlterField(
            model_name='radarsnapshot',
            name='save_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='salvataggio'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=64, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Nation', verbose_name='nazione'),
        ),
        migrations.AlterField(
            model_name='region',
            name='rank',
            field=models.IntegerField(verbose_name='importanza'),
        ),
        migrations.AlterField(
            model_name='station',
            name='active',
            field=models.BooleanField(default=True, verbose_name='attiva'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='indirizzo'),
        ),
        migrations.AlterField(
            model_name='station',
            name='cap',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='cap'),
        ),
        migrations.AlterField(
            model_name='station',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='città/comune'),
        ),
        migrations.AlterField(
            model_name='station',
            name='climate',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='clima'),
        ),
        migrations.AlterField(
            model_name='station',
            name='data_date_format',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='formato data (python)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='data_format',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.DataFormat', verbose_name='formato dati'),
        ),
        migrations.AlterField(
            model_name='station',
            name='data_time_format',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='formato ora (python)'),
        ),
        migrations.AlterField(
            model_name='station',
            name='data_url',
            field=models.URLField(max_length=255, verbose_name='url dati'),
        ),
        migrations.AlterField(
            model_name='station',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='descrizione'),
        ),
        migrations.AlterField(
            model_name='station',
            name='elevation',
            field=models.IntegerField(verbose_name='altitudine'),
        ),
        migrations.AlterField(
            model_name='station',
            name='elevation_ground',
            field=models.IntegerField(verbose_name='elevazione dal suolo'),
        ),
        migrations.AlterField(
            model_name='station',
            name='forecast_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='url sito previsionale'),
        ),
        migrations.AlterField(
            model_name='station',
            name='installation_position',
            field=models.CharField(max_length=255, verbose_name='posizionamento'),
        ),
        migrations.AlterField(
            model_name='station',
            name='installation_type',
            field=models.CharField(max_length=255, verbose_name='tipo intallazione'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.CharField(max_length=255, verbose_name='latitudine'),
        ),
        migrations.AlterField(
            model_name='station',
            name='lng',
            field=models.CharField(max_length=255, verbose_name='longitudine'),
        ),
        migrations.AlterField(
            model_name='station',
            name='mean_year_rain',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pioggia media annua'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=128, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='station',
            name='nation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.Nation', verbose_name='nazione'),
        ),
        migrations.AlterField(
            model_name='station',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.Province', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='station',
            name='ranking',
            field=models.IntegerField(default=1, verbose_name='ranking'),
        ),
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtime.Region', verbose_name='regione'),
        ),
        migrations.AlterField(
            model_name='station',
            name='short_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='nome abbreviato'),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(max_length=128, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='station',
            name='software_model',
            field=models.CharField(max_length=255, verbose_name='software'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_model',
            field=models.CharField(max_length=255, verbose_name='modello stazione'),
        ),
        migrations.AlterField(
            model_name='station',
            name='web',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='sito web'),
        ),
        migrations.AlterField(
            model_name='station',
            name='webcam',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='webcam url'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='data',
            field=models.TextField(verbose_name='json data'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='icona'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='last_edit',
            field=models.DateTimeField(verbose_name='ultima modifica'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='period',
            field=models.IntegerField(choices=[(0, '00:00 06:00'), (1, '06:00 12:00'), (2, '12:00 18:00'), (3, '18:00 24:00')], verbose_name='periodo'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtime.Station', verbose_name='stazione'),
        ),
        migrations.AlterField(
            model_name='stationforecast',
            name='text',
            field=models.CharField(max_length=50, verbose_name='testo'),
        ),
    ]
