# Generated by Django 2.2.1 on 2020-12-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0019_auto_20201217_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualitystation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='air_quality_stations', to='realtime.Station', verbose_name='stazione meteo'),
        ),
    ]
