# Generated by Django 2.2.1 on 2020-12-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0020_airqualitystation_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitystation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airquality_stations', to='realtime.Station', verbose_name='stazione meteo'),
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='data e ora')),
                ('air_quality_index', models.IntegerField(verbose_name="indice qualità dell'aria")),
                ('pm1', models.IntegerField(verbose_name='pm 1')),
                ('pm1_max', models.IntegerField(verbose_name='pm 1 massimo')),
                ('pm1_max_time', models.TimeField(blank=True, null=True, verbose_name='ora pm 1 massimo')),
                ('pm1_min', models.IntegerField(verbose_name='pm 1 minimo')),
                ('pm1_min_time', models.TimeField(blank=True, null=True, verbose_name='ora pm 1 massimo')),
                ('pm25', models.IntegerField(verbose_name='pm 2.5')),
                ('pm25_max', models.IntegerField(verbose_name='pm 2.5 massimo')),
                ('pm25_max_time', models.TimeField(blank=True, null=True, verbose_name='ora pm 2.5 massimo')),
                ('pm25_min', models.IntegerField(verbose_name='pm 2.5 minimo')),
                ('pm25_min_time', models.TimeField(blank=True, null=True, verbose_name='ora pm 2.5 minimo')),
                ('pm10', models.IntegerField(verbose_name='pm 10')),
                ('pm10_max', models.IntegerField(verbose_name='pm 10 massimo')),
                ('pm10_max_time', models.TimeField(blank=True, null=True, verbose_name='ora pm 10 massimo')),
                ('pm10_min', models.IntegerField(verbose_name='pm 10 minimo')),
                ('pm10_min_time', models.TimeField(blank=True, null=True, verbose_name='ora pm 10 minimo')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='realtime.AirQualityStation', verbose_name='stazione')),
            ],
            options={
                'verbose_name': "Dati qualità dell'aria",
                'verbose_name_plural': "Dati qualità dell'aria",
            },
        ),
    ]
