# Generated by Django 2.2.1 on 2020-12-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0021_auto_20201218_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydata',
            name='air_quality_index',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name="indice qualità dell'aria"),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm1',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 1'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm10',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 10'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm10_max',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 10 massimo'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm10_min',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 10 minimo'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm1_max',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 1 massimo'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm1_min',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 1 minimo'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm25',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 2.5'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm25_max',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 2.5 massimo'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='pm25_min',
            field=models.DecimalField(decimal_places=1, max_digits=8, verbose_name='pm 2.5 minimo'),
        ),
    ]
