# Generated by Django 2.2.1 on 2023-04-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0023_historicairqualitydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='data_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='token url dati'),
        ),
    ]
