"""
Django settings for TorinoMeteo project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from dotenv import load_dotenv
from getenv import env


def here(*x):
    return os.path.join(
        os.path.dirname(os.path.realpath(__file__)), *x
    )

BASE_DIR = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)

dotenv_path = here('..', '..', '.env')
load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'SECRET_KEY',
    '49saa%ruey1&!nveiz*f(cu$)0pje8wz7u++y-0ljd2)9r)j8h'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

ADMINS = (
    ('abidibo', 'abidibo@gmail.com'),
)

# SITE
SITE_ID = 1
HTTPS = False

# MAIL
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
NOREPLY_EMAIL = 'noreply@torinometeo.org'
NET_REQUEST_EMAIL = 'info@torinometeo.org'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME', 'dbtorinometeo'),
        'HOST': env('DB_HOST', 'localhost'),
        'USER': env('DB_USER', 'torinometeo'),
        'PASSWORD': env('DB_PASSWORD', required=True),
        'PORT': '',
        'OPTIONS': {
            'init_command': 'SET default_storage_engine=InnoDB',
        }
    }
}

# Application definition

INSTALLED_APPS = (
    'core',
    'suit',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.flatpages',
    'ckeditor',
    'ckeditor_uploader',
    'pipeline',
    'corsheaders',
    'filer',
    'mptt',
    'easy_thumbnails',
    'django_cleanup',
    'captcha',
    'sorl.thumbnail',
    'disqus',
    'taggit',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'treenav',
    # tm
    'forecast',
    'realtime',
    'blog',
    'webcam',
)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
)

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': False,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'treenav.context_processors.treenav_active',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'it-it'

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_STORAGE = 'pipeline.storage.PipelineCachedStorage'
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Uploaded files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_FORECAST_IMG_REL = 'forecast/img'
MEDIA_REALTIME_STATION_IMG_REL = 'realtime/station/img'
MEDIA_REALTIME_NET_REQUEST_IMG_REL = 'realtime/net_request/img'
MEDIA_BLOG_IMG_REL = 'blog/img'
MEDIA_WEBCAM_IMG_REL = 'webcam/img'

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    )
}

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'name': 'Authorization',  # set 'Token token-hash' in authorize
            'in': 'header'
        }
    },
    'JSON_EDITOR': True
}

# CORS HEADERS
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

# ADMIN

SUIT_CONFIG = {
    'ADMIN_NAME': 'TorinoMeteo',
    'MENU': (

        '-',

        {'app': 'auth', 'label': 'Authentication', 'icon': 'fa fa-lock'},
        {'app': 'authtoken', 'label': 'REST token authentication',
         'icon': 'fa fa-lock'},
        {'app': 'sites', 'label': 'Sites', 'icon': 'fa fa-leaf'},

        '-',

        {'app': 'treenav', 'label': 'Menu', 'icon': 'fa fa-bars'},

        '-',

        {'app': 'filer', 'label': 'Files', 'icon': 'fa fa-file'},


        '-',

        {'app': 'flatpages', 'label': 'Pagine', 'icon': 'fa fa-file-text-o'},
        {'app': 'blog', 'label': 'Blog', 'icon': 'fa fa-book'},

        '-',

        {'app': 'realtime', 'label': 'Realtime', 'icon': 'fa fa-clock-o'},
        {'app': 'forecast', 'label': 'Previsioni', 'icon': 'fa fa-globe'},
        {'app': 'webcam', 'label': 'Webcam', 'icon': 'fa fa-camera'},

    )
}


# CKEDITOR
CKEDITOR_UPLOAD_PATH = 'ckeditor/'
CKEDITOR_JQUERY_URL = ''
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono',
        'toolbar_Basic': [
                ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_Full': [
            ['Styles', 'Format', 'Bold', 'Italic', 'Underline',
                'Strike', 'SpellChecker', 'Undo', 'Redo'],
            ['NumberedList', 'BulletedList'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['SpecialChar'], ['PasteFromWord'], ['Source']
        ],
        'toolbar': 'Full',
        'height': 291,
        'width': 835,
        'filebrowserWindowWidth': 940,
        'filebrowserWindowHeight': 725,
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'extraAllowedContent': 'iframe[*]',
        'stylesSet': 'core_styles:/static/core/src/js/ckeditor_styles.js',
    }
}

# pipeline
PIPELINE_CSS = {
    'vendor': {
        'source_filenames': (
            'core/src/vendor/Font-Awesome/scss/font-awesome.scss',
            'core/src/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css', # noqa
        ),
        'output_filename': 'core/css/vendor.min.css',
    },
    'torinometeo': {  # bootstrap + custom
        'source_filenames': (
            'core/src/scss/styles.scss',
        ),
        'output_filename': 'core/css/core.min.css',
    },
    'api': {  # api
        'source_filenames': (
            'core/src/scss/api/styles.scss',
        ),
        'output_filename': 'core/css/api.min.css',
    },
}
PIPELINE_JS = {
    'vendor': {
        'source_filenames': (
            'core/src/vendor/bootstrap/js/tether.js',
            'core/src/vendor/bootstrap/js/bootstrap.min.js',
            'core/src/vendor/moment/moment-with-locales.min.js',
            'core/src/vendor/bootstrap-material-design/scripts/ripples.js',
            'core/src/vendor/bootstrap-material-design/scripts/material.js',
            'core/src/vendor/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js', # noqa
        ),
        'output_filename': 'core/js/vendor.min.js'
    },
    'torinometeo': {
        'source_filenames': (
            'core/src/js/core.js',
            'core/src/js/realtime_jumbotron.js',
        ),
        'output_filename': 'core/js/core.min.js'
    },
}

PIPELINE_COMPILERS = (
    'pipeline.compilers.sass.SASSCompiler',
)
PIPELINE_CSS_COMPRESSOR = None
PIPELINE_JS_COMPRESSOR = None


# Disqus
DISQUS_API_KEY = 'kjNmaqKMTwg388VnEJicaYV1jdteFZYQLQcsvQwmQJth4V2LpW9lJ3sfgSsxN4YP' # noqa
DISQUS_WEBSITE_SHORTNAME = 'torinometeo'

THUMBNAIL_HIGH_RESOLUTION = True
THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    # 'easy_thumbnails.processors.scale_and_crop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters',
)


# LOGGING

LOGGING_DEFAULT = {
    'handlers': ['console', 'file'],
    'level': 'DEBUG',
    'propagate': True,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s' #  noqa
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'django.utils.log.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        #  configure the log to be rotated daily
        #  see
        #  noqa https://docs.python.org/2.7/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler
        'file': {
            'level': 'DEBUG',
            'formatter': 'verbose',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': here('..',
                             '..',
                             '..',
                             os.path.join('logs', 'debug.log')
                             ),
            'when':     'midnight',
        },
        'celery_logger': {
            'level': 'DEBUG',
            'filters': None,
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': here('..', '..', '..',
                             os.path.join('logs', 'celery.log')),
            'formatter': 'verbose'
        },
        'realtime_celery_logger': {
            'level': 'DEBUG',
            'filters': None,
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': here('..', '..', '..',
                             os.path.join('logs', 'realtime.log')),
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins', 'console', 'file', ],
            'level': 'ERROR',
            'propagate': False,
        },
        # noqa http://stackoverflow.com/questions/7768027/turn-off-sql-logging-while-keeping-settings-debug
       'django.db.backends': {
            'handlers': ['null'],  # Quiet by default!
            'propagate': False,
            'level': 'DEBUG',
        },
        'celery': {
            'handlers': ['celery_logger'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'celery.tasks': {
            'handlers': ['celery_logger'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'realtime.tasks': {
            'handlers': ['realtime_celery_logger', ],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': LOGGING_DEFAULT,
        '': LOGGING_DEFAULT,  # root logger
    },
}
